# 1. build the docker image
# 2. Push the docker image to docker "on"
# 3. SSH into our VM and start our new Image

name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: lostisdead/user-app-backend:${{ github.sha }}
#step to deploy to the VM is remaining
